/*
* Private Syscall
*/
const char * mach_syscall_name_table[128] = {
	/* 0 */		"kern_invalid",
	/* 1 */		"kern_invalid",
	/* 2 */		"kern_invalid",
	/* 3 */		"kern_invalid",
	/* 4 */		"kern_invalid",
	/* 5 */		"kern_invalid",
	/* 6 */		"kern_invalid",
	/* 7 */		"kern_invalid",
	/* 8 */		"kern_invalid",
	/* 9 */		"kern_invalid",
	/* 10 */	"_kernelrpc_mach_vm_allocate_trap", // OS X : "kern_invalid",
	/* 11 */	"_kernelrpc_vm_allocate_trap", // OS X : "kern_invalid",
	/* 12 */	"_kernelrpc_mach_vm_deallocate_trap", // OS X: "kern_invalid",
	/* 13 */	"_kernelrpc_vm_deallocate_trap" , // "kern_invalid",
	/* 14 */	"_kernelrpc_mach_vm_protect_trap", //"kern_invalid",
	/* 15 */	"_kernelrpc_vm_protect_trap", // kern_invalid",
	/* 16 */	"_kernelrpc_mach_port_allocate_trap", //"kern_invalid",
	/* 17 */	"_kernelrpc_mach_port_destroy_trap" ,//"kern_invalid",
	/* 18 */	"_kernelrpc_mach_port_deallocate_trap", // "kern_invalid",
	/* 19 */	"_kernelrpc_mach_port_mod_refs_trap", //"kern_invalid",
	/* 20 */	"_kernelrpc_mach_port_move_member_trap", //"kern_invalid",
	/* 21 */	"_kernelrpc_mach_port_insert_right_trap", //"kern_invalid",
	/* 22 */	"_kernelrpc_mach_port_insert_member_trap", // "kern_invalid",
	/* 23 */	"_kernelrpc_mach_port_extract_member_trap", // "kern_invalid",
	/* 24 */	"kern_invalid",
	/* 25 */	"kern_invalid",
	/* 26 */	"mach_reply_port",
	/* 27 */	"thread_self_trap",
	/* 28 */	"task_self_trap",
	/* 29 */	"host_self_trap",
	/* 30 */	"kern_invalid",
	/* 31 */	"mach_msg_trap",
	/* 32 */	"mach_msg_overwrite_trap",
	/* 33 */	"semaphore_signal_trap",
	/* 34 */	"semaphore_signal_all_trap",
	/* 35 */	"semaphore_signal_thread_trap",
	/* 36 */	"semaphore_wait_trap",
	/* 37 */	"semaphore_wait_signal_trap",
	/* 38 */	"semaphore_timedwait_trap",
	/* 39 */	"semaphore_timedwait_signal_trap",
	/* 40 */	"kern_invalid",
	/* 41 */	"kern_invalid",
	/* 42 */	"kern_invalid",
	/* 43 */	"map_fd",
	/* 44 */	"task_name_for_pid",
	/* 45 */ 	"task_for_pid",
	/* 46 */	"pid_for_task",
	/* 47 */	"kern_invalid",
	/* 48 */	"macx_swapon",
	/* 49 */	"macx_swapoff",
	/* 50 */	"kern_invalid",
	/* 51 */	"macx_triggers",
	/* 52 */	"macx_backing_store_suspend",
	/* 53 */	"macx_backing_store_recovery",
	/* 54 */	"kern_invalid",
	/* 55 */	"kern_invalid",
	/* 56 */	"kern_invalid",
	/* 57 */	"kern_invalid",
	/* 58 */	"pfz_exit",
	/* 59 */ 	"swtch_pri",
	/* 60 */	"swtch",
	/* 61 */	"thread_switch",
	/* 62 */	"clock_sleep_trap",
	/* 63 */	"kern_invalid",
	/* traps 64 - 95 reserved (debo) */
	/* 64 */	"kern_invalid",
	/* 65 */	"kern_invalid",
	/* 66 */	"kern_invalid",
	/* 67 */	"kern_invalid",
	/* 68 */	"kern_invalid",
	/* 69 */	"kern_invalid",
	/* 70 */	"kern_invalid",
	/* 71 */	"kern_invalid",
	/* 72 */	"kern_invalid",
	/* 73 */	"kern_invalid",
	/* 74 */	"kern_invalid",
	/* 75 */	"kern_invalid",
	/* 76 */	"kern_invalid",
	/* 77 */	"kern_invalid",
	/* 78 */	"kern_invalid",
	/* 79 */	"kern_invalid",
	/* 80 */	"kern_invalid",
	/* 81 */	"kern_invalid",
	/* 82 */	"kern_invalid",
	/* 83 */	"kern_invalid",
	/* 84 */	"kern_invalid",
	/* 85 */	"kern_invalid",
	/* 86 */	"kern_invalid",
	/* 87 */	"kern_invalid",
	/* 88 */	"kern_invalid",
	/* 89 */	"mach_timebase_info_trap",
	/* 90 */	"mach_wait_until_trap",
	/* 91 */	"mk_timer_create_trap",
	/* 92 */	"mk_timer_destroy_trap",
	/* 93 */	"mk_timer_arm_trap",
	/* 94 */	"mk_timer_cancel_trap",
	/* 95 */	"kern_invalid",
	/* traps 64 - 95 reserved (debo) */
	/* 96 */	"kern_invalid",
	/* 97 */	"kern_invalid",
	/* 98 */	"kern_invalid",
	/* 99 */	"kern_invalid",
	/* traps 100-107 reserved for iokit (esb) */ 
	/* 100 */	"kern_invalid",
	/* 100 */	//"iokit_user_client_trap",
	/* 101 */	"kern_invalid",
	/* 102 */	"kern_invalid",
	/* 103 */	"kern_invalid",
	/* 104 */	"kern_invalid",
	/* 105 */	"kern_invalid",
	/* 106 */	"kern_invalid",
	/* 107 */	"kern_invalid",
	/* traps 108-127 unused */			
	/* 108 */	"kern_invalid",
	/* 109 */	"kern_invalid",
	/* 110 */	"kern_invalid",
	/* 111 */	"kern_invalid",
	/* 112 */	"kern_invalid",
	/* 113 */	"kern_invalid",
	/* 114 */	"kern_invalid",
	/* 115 */	"kern_invalid",
	/* 116 */	"kern_invalid",
	/* 117 */	"kern_invalid",
	/* 118 */	"kern_invalid",
	/* 119 */	"kern_invalid",
	/* 120 */	"kern_invalid",
	/* 121 */	"kern_invalid",
	/* 122 */	"kern_invalid",
	/* 123 */	"kern_invalid",
	/* 124 */	"kern_invalid",
	/* 125 */	"kern_invalid",
	/* 126 */	"kern_invalid",
	/* 127 */	"kern_invalid",
};


/* 
* Posix syscall 
*/
#define SYS_MAXSYSCALL   	443
#define SYS_MAXSYSCALL_7	454

char *syscall_names[] = {
	"syscall", 				/* 0 */
	"exit", 
	"fork", 
	"read",
	"write", 
	"open", 
	"close", 
	"wait4", 
	"8  old creat", 
	"link", 
	"unlink", 					/* 10 */
	"11  old execv", 
	"chdir", 
	"fchdir", 
	"mknod", 
	"chmod", 
	"chown", 
	"17  old break", 
	"getfsstat", 
	"19  old lseek", 
	"getpid", 					/* 20 */
	"21  old mount", 
	"22  old umount", 
	"setuid", 
	"getuid", 
	"geteuid", 
	"ptrace", 
	"recvmsg", 
	"sendmsg", 
	"recvfrom", 
	"accept", 					/* 30 */
	"getpeername", 
	"getsockname", 
	"access", 
	"chflags", 
	"fchflags", 
	"sync", 
	"kill", 
	"38  old stat", 
	"getppid", 
	"40  old lstat", 			/* 40 */
	"dup", 
	"pipe", 
	"getegid", 
	"profil", 
	"45  old ktrace", 
	"sigaction", 
	"getgid", 
	"sigprocmask", 
	"getlogin", 
	"setlogin", 				/* 50 */
	"acct", 
	"sigpending", 
	"sigaltstack", 
	"ioctl", 
	"reboot", 
	"revoke", 
	"symlink", 
	"readlink", 
	"execve", 
	"umask", 				/* 60 */
	"chroot", 
	"62  old fstat", 
	"63  used internally , reserved", 
	"64  old getpagesize", 
	"msync", 
	"vfork", 
	"67  old vread", 
	"68  old vwrite", 
	"69  old sbrk", 
	"70  old sstk", 			/* 70 */
	"71  old mmap", 
	"72  old vadvise", 
	"munmap", 
	"mprotect", 
	"madvise", 
	"76  old vhangup", 
	"77  old vlimit", 
	"mincore", 
	"getgroups", 
	"setgroups",				/* 80 */ 
	"getpgrp", 
	"setpgid", 
	"setitimer", 
	"84  old wait", 
	"swapon", 
	"getitimer", 
	"87  old gethostname", 
	"88  old sethostname", 
	"getdtablesize", 
	"dup2", 					/* 90 */
	"91  old getdopt", 
	"fcntl", 
	"select", 
	"94  old setdopt", 
	"fsync", 
	"setpriority", 
	"socket", 
	"connect", 
	"99  old accept", 
	"getpriority", 				/* 100 */
	"101  old send", 
	"102  old recv",
	"103  old sigreturn",
	"bind", 
	"setsockopt", 
	"listen", 
	"107  old vtimes", 
	"108  old sigvec", 
	"109  old sigblock", 
	"110  old sigsetmask", 		/* 110 */
	"sigsuspend", 
	"112  old sigstack", 
	"113  old recvmsg", 
	"114  old sendmsg", 
	"115  old vtrace", 
	"gettimeofday", 
	"getrusage", 
	"getsockopt", 
	"119  old resuba", 
	"readv", 					/* 120 */
	"writev", 
	"settimeofday", 
	"fchown", 
	"fchmod", 
	"125  old recvfrom", 
	"setreuid", 
	"setregid", 
	"rename", 
	"129  old truncate", 
	"130  old ftruncate", 		/* 130 */
	"flock", 
	"mkfifo", 
	"sendto", 
	"shutdown", 
	"socketpair", 
	"mkdir", 
	"rmdir", 
	"utimes", 
	"futimes", 
	"adjtime",				/* 140 */ 
	"141  old getpeername", 
	"gethostuuid", 
	"143  old sethostid", 
	"144  old getrlimit",
	"145  old setrlimit", 
	"146  old killpg", 
	"setsid", 
	"148  old setquota", 
	"149  old qquota", 
	"150  old getsockname", 	/* 150 */
	"getpgid", 
	"setprivexec", 
	"pread", 
	"pwrite", 
	"nfssvc", 
	"156  old getdirentries", 
	"statfs", 
	"fstatfs", 
	"unmount", 
	"160  old async_daemon", 	/* 160 */
	"getfh", 
	"162  old getdomainname", 
	"163  old setdomainname", 
	"164", 
	"quotactl", 
	"166  old exportfs", 
	"mount", 
	"168  old ustat", 
	"csops", 
	"csops_audittoken", 		/* 170 */
	"171  old wait3", 
	"172  old rpause", 
	"waitid", 
	"174  old getdents", 
	"175  old gc_control", 
	"add_profil", 
	"177", 
	"178", 
	"179", 
	"kdebug_trace", 			/* 180 */
	"setgid", 
	"setegid", 
	"seteuid", 
	"sigreturn", 
	"chud", 
	"186", 
	"fdatasync", 
	"stat", 
	"fstat", 
	"lstat", 					/* 190 */
	"pathconf", 
	"fpathconf", 
	"193", 
	"getrlimit", 
	"setrlimit", 
	"getdirentries", 
	"mmap", 
	"198  __syscall", 
	"lseek", 
	"truncate", 				/* 200 */
	"ftruncate", 
	"__sysctl", 
	"mlock", 
	"munlock", 
	"undelete", 
	"ATsocket", 
	"ATgetmsg", 
	"ATputmsg", 
	"ATPsndreq", 
	"ATPsndrsp", 				/* 210 */
	"ATPgetreq", 
	"ATPgetrsp", 
	"213  Reserved for AppleTalk", 
	"214", 
	"215", 
	"mkcomplex", 
	"statv", 
	"lstatv", 
	"fstatv", 
	"getattrlist", 				/* 220 */
	"setattrlist", 
	"getdirentriesattr", 
	"exchangedata", 
	"224  old checkuseraccess / fsgetpath ( which moved to 427 )", 
	"searchfs", 
	"delete", 
	"copyfile", 
	"fgetattrlist", 
	"fsetattrlist", 
	"poll", 					/* 230 */
	"watchevent", 
	"waitevent", 
	"modwatch", 
	"getxattr", 
	"fgetxattr", 
	"setxattr", 
	"fsetxattr", 
	"removexattr", 
	"fremovexattr", 
	"listxattr",				/* 240 */
	"flistxattr", 
	"fsctl", 
	"initgroups", 
	"posix_spawn", 
	"ffsctl", 
	"246", 
	"nfsclnt", 
	"fhopen", 
	"249", 
	"minherit", 				/* 250 */
	"semsys", 
	"msgsys", 
	"shmsys", 
	"semctl", 
	"semget", 
	"semop", 
	"257", 
	"msgctl", 
	"msgget", 
	"msgsnd", 				/* 260 */
	"msgrcv", 
	"shmat", 
	"shmctl", 
	"shmdt", 
	"shmget", 
	"shm_open", 
	"shm_unlink", 
	"sem_open", 
	"sem_close", 
	"sem_unlink", 				/* 270 */
	"sem_wait", 
	"sem_trywait", 
	"sem_post", 
	"sem_getvalue", 
	"sem_init", 
	"sem_destroy", 
	"open_extended", 
	"umask_extended", 
	"stat_extended", 
	"lstat_extended", 			/* 280 */
	"fstat_extended", 
	"chmod_extended", 
	"fchmod_extended", 
	"access_extended", 
	"settid", 
	"gettid", 
	"setsgroups", 
	"getsgroups", 
	"setwgroups", 
	"getwgroups", 			/* 290 */
	"mkfifo_extended", 
	"mkdir_extended", 
	"identitysvc", 
	"shared_region_check_np", 
	"shared_region_map_np", 
	"vm_pressure_monitor", 
	"psynch_rw_longrdlock", 
	"psynch_rw_yieldwrlock", 
	"psynch_rw_downgrade", 
	"psynch_rw_upgrade", 		/* 300 */
	"psynch_mutexwait", 
	"psynch_mutexdrop", 
	"psynch_cvbroad", 
	"psynch_cvsignal", 
	"psynch_cvwait", 
	"psynch_rw_rdlock", 
	"psynch_rw_wrlock", 
	"psynch_rw_unlock", 
	"psynch_rw_unlock2", 
	"getsid", 					/* 310 */
	"settid_with_pid", 
	"psynch_cvclrprepost", 
	"aio_fsync", 
	"aio_return", 
	"aio_suspend", 
	"aio_cancel", 
	"aio_error", 
	"aio_read", 
	"aio_write", 
	"lio_listio", 				/* 320 */
	"321  old __pthread_cond_wait", 
	"iopolicysys", 
	"process_policy", 
	"mlockall", 
	"munlockall", 
	"326", 
	"issetugid", 
	"__pthread_kill", 
	"__pthread_sigmask", 
	"__sigwait", 				/* 330 */
	"__disable_threadsignal", 
	"__pthread_markcancel", 
	"__pthread_canceled", 
	"__semwait_signal", 
	"335  old utrace", 
	"proc_info", 
	"sendfile", 
	"stat64", 
	"fstat64", 
	"lstat64",					/* 340 */
	"stat64_extended",
	"lstat64_extended", 
	"fstat64_extended", 
	"getdirentries64", 
	"statfs64", 
	"fstatfs64", 
	"getfsstat64", 
	"__pthread_chdir", 
	"__pthread_fchdir", 
	"audit", 					/* 350 */
	"auditon",
	"352", 
	"getauid", 
	"setauid", 
	"getaudit", 
	"setaudit", 
	"getaudit_addr", 
	"setaudit_addr", 
	"auditctl", 
	"bsdthread_create",		/* 360 */
	"bsdthread_terminate",
	"kqueue", 
	"kevent", 
	"lchown", 
	"stack_snapshot", 
	"bsdthread_register", 
	"workq_open", 
	"workq_kernreturn", 
	"kevent64", 
	"__old_semwait_signal", 	/* 370 */
	"__old_semwait_signal_nocancel",
	"thread_selfid", 
	"ledger", 
	"374", 
	"375", 
	"376", 
	"377", 
	"378", 
	"379",
	"__mac_execve", 			/* 380 */
	"__mac_syscall", 
	"__mac_get_file", 
	"__mac_set_file", 
	"__mac_get_link", 
	"__mac_set_link", 
	"__mac_get_proc", 
	"__mac_set_proc", 
	"__mac_get_fd", 
	"__mac_set_fd", 
	"__mac_get_pid", 			/* 390 */
	"__mac_get_lcid", 
	"__mac_get_lctx", 
	"__mac_set_lctx", 
	"setlcid", 
	"getlcid", 
	"read_nocancel", 
	"write_nocancel", 
	"open_nocancel", 
	"close_nocancel", 
	"wait4_nocancel", 			/* 400 */
	"recvmsg_nocancel", 
	"sendmsg_nocancel", 
	"recvfrom_nocancel", 
	"accept_nocancel", 
	"msync_nocancel", 
	"fcntl_nocancel", 
	"select_nocancel", 
	"fsync_nocancel", 
	"connect_nocancel", 
	"sigsuspend_nocancel", 		/* 410 */
	"readv_nocancel", 
	"writev_nocancel", 
	"sendto_nocancel", 
	"pread_nocancel", 
	"pwrite_nocancel", 
	"waitid_nocancel", 
	"poll_nocancel", 
	"msgsnd_nocancel", 
	"msgrcv_nocancel", 
	"sem_wait_nocancel", 		/* 420 */
	"aio_suspend_nocancel",
	"__sigwait_nocancel", 
	"__semwait_signal_nocancel", 
	"__mac_mount", 
	"__mac_get_mount", 
	"__mac_getfsstat", 
	"fsgetpath", 
	"audit_session_self", 
	"audit_session_join", 
	"fileport_makeport", 		/* 430 */
	"fileport_makefd", 
	"audit_session_port",
	"pid_suspend", 
	"pid_resume", 
	"pid_hibernate", 
	"pid_shutdown_sockets", 
	"437  old shared_region_slide_np", 
	"shared_region_map_and_slide_np" , 
	"kas_info", 
	"memorystatus_control", 	/*440 */
	"guarded_open_np",
	"guarded_close_np",
	"guarded_kqueue_np",		/* 443 */
	"change_fdguard_np", 
	"old __proc_suppress", 
	"proc_rlimit_control", 
	"proc_connectx", 
	"proc_disconnectx", 
	"proc_peeloff",
	"proc_socket_delegate",		/* 450 */
	"proc_telemetry",
	"proc_uuid_policy",
	"memorystatus_get_level",	/* 453 */
	NULL
};
